#ifndef LIB_SURGICAL_TOOL_TYPE_H_LF
#define LIB_SURGICAL_TOOL_TYPE_H_LF

enum SurgicalToolType
{
    SURGICAL_TOOL_TYPE_ENDOSCOPIC,
    SURGICAL_TOOL_TYPE_SP_TOOL,
    SURGICAL_TOOL_TYPE_UNKNOWN
};

#endif // LIB_SURGICAL_TOOL_TYPE_H_LF
