#ifndef LIB_INSTRUMENT_TYPE_H_LF
#define LIB_INSTRUMENT_TYPE_H_LF

enum InstrumentType
{
	INSTRUMENT_TYPE_LAPAROSCOPE,
	INSTRUMENT_TYPE_SP_TOOL,
	INSTRUMENT_TYPE_UNKNOWN
};

#endif // LIB_INSTRUMENT_TYPE_H_LF